apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e9xlj2f66-go
  janus-idp.io/tekton: e9xlj2f66-go
  backstage.io/kubernetes-id: e9xlj2f66-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e9xlj2f66-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
